#!/usr/bin/env bash
# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

set -euf -o pipefail

if [[ $# -ge 1 ]]; then
  readonly OS="${1}"
  if [[ "$OS" != "mac" && "$OS" != "linux" ]]; then
    echo "Usage: ${0} <os> <ref> <version>" 1>&2
    echo "<os> can be 'mac' or 'linux'" 1>&2
    exit 1
  fi
else
  echo "Usage: ${0} <os> <ref> <version>" 1>&2
  exit 1
fi

if [[ $# -ge 2 ]]; then
  readonly REF="${2}"
else
  echo "Usage: ${0} <os> <ref> <version>" 1>&2
  exit 1
fi

if [[ $# -eq 3 ]]; then
  readonly VERSION="${3}"
else
  echo "Usage: ${0} <os> <ref> <version>" 1>&2
  exit 1
fi

cipd set-ref "fuchsia/tools/jiri/${OS}-amd64" -ref "${REF}" -version "${VERSION}"
